# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{swf_file}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["DBA"]
  s.date = %q{2010-05-06}
  s.description = %q{Based on the swfutil lib, by Dennis Zhuang, the SWF File is lightweight gem to read swf file headers from within a Ruby application. This gem is fully written in Ruby and is compatible with Ruby v1.9.x}
  s.email = %q{dba@gnomeslab.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "fixtures/clicktag-decompressed.swf",
     "fixtures/clicktag.swf",
     "fixtures/smallgoat.jpg",
     "lib/swf_file.rb",
     "lib/swf_file/compression.rb",
     "lib/swf_file/conversions.rb",
     "lib/swf_file/packed_bit_object.rb",
     "lib/swf_file/parser.rb",
     "lib/swf_file/swf_header.rb",
     "test/test_helper.rb",
     "test/unit/swf_file_test.rb"
  ]
  s.homepage = %q{http://github.com/DBA/swf_file}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{SWF File is lightweight gem to read swf file headers from within a Ruby application}
  s.test_files = [
    "test/test_helper.rb",
     "test/unit/swf_file_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

